# Generated by Django 4.2.1 on 2023-07-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_articulo_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='stock',
        ),
        migrations.AddField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
    ]
