# Generated by Django 4.2.1 on 2023-07-13 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_remove_articulo_stock_articulo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fechaCompra',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id_boleta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.BigIntegerField(verbose_name='Total'),
        ),
    ]
