# Generated by Django 4.2.1 on 2023-07-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_alter_boleta_fechacompra_alter_boleta_id_boleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuario'),
        ),
    ]
