# Generated by Django 4.2.1 on 2023-07-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_boleta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='estado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuario'),
        ),
    ]
