# Generated by Django 4.2.1 on 2023-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_boleta_estado_detalle_boleta_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='usuario',
        ),
    ]
