# Generated by Django 4.2.1 on 2023-07-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0010_remove_detalle_boleta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='envio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Envio'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='impuesto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Impuesto'),
        ),
    ]
